# This is a basic workflow to help you get started with Actions

name: Build Android and iOS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - './mobile-app/**'
  pull_request:
    branches: [ master ]
    paths:
    - './mobile-app/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install --frozen-lockfile
        working-directory: ./mobile-app
      - name: Run tests
        run: |
          yarn test
        working-directory: ./mobile-app
  build-ios:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install --frozen-lockfile
        working-directory: ./mobile-app
      - name: Install pod dependencies
        run: |
          cd ios && pod install && cd ..
        working-directory: ./mobile-app
      - name: Run tests
        run: |       
          yarn test
        working-directory: ./mobile-app
